### ISSUE TITLE
[BUG] Users shouldn't edit any transactionId

### ISSUE THREAD

**Issue by manuelalferez** [manuelalferez/flowinance#70]
### Verify this issue hasn't been reported before

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### What

When users are on the `/transactions/update`?id=84 page, they can modify the ID, and we currently do not verify whether that ID belongs to them

### Steps to Reproduce

1. Navigate to [https://flowinance.com/transactions/update](https://flowinance.com/transactions/update).
2. Change the ID in the URL bar to a different value.

<p align="center">
  <img src="https://github.com/user-attachments/assets/32db81e3-ab07-465a-a380-a9dc896fb67d" width="500" alt="Screenshot of the issue">
</p>

### Do you want to work on this issue?

No

**Comment by swarupn17** [comment]
Hey @manuelalferez I can do this task. Please can you assign it to me.
Thanks !

**Comment by swarupn17** [comment]
Hey @manuelalferez while running the website locally using "npm run dev" i encountered following error please can you help me. I installed all the dependencies.
ERROR:
(node:35027) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:35016) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
- error node_modules/@supabase/auth-helpers-nextjs/dist/index.js (237:10) @ createServerComponentClient
- error Error: either NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY env variables or supabaseUrl and supabaseKey are required!
    at eval (./src/app/supabase-server.tsx:15:175)
    at getSession (./src/app/supabase-server.tsx:19:22)
    at RootLayout (./src/app/layout.tsx:34:87)
null
- error node_modules/@supabase/auth-helpers-nextjs/dist/index.js (237:10) @ createServerComponentClient
- error Error: either NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY env variables or supabaseUrl and supabaseKey are required!
    at eval (./src/app/supabase-server.tsx:15:175)
    at getSession (./src/app/supabase-server.tsx:19:22)
    at RootLayout (./src/app/layout.tsx:34:87)
digest: "436353347"
null

**Comment by manuelalferez** [comment]
@swarupn17 have you been able to run Supabase locally? More info here: https://supabase.com/docs/guides/local-development/cli/getting-started

The error that you are encountering is informing you that later you should include the env variables that your local supabase will provide to you, into the `.env.local` files, with the rest of the env variables. If you need help let me know

**Comment by manuelalferez** [comment]
hi @swarupn17, I have improved the documentation regarding the issues that contributors are facing with the configuration of the project in this PR: https://github.com/manuelalferez/flowinance/pull/95. Also, check out the new documentation [here](https://github.com/manuelalferez/flowinance/blob/main/README.md#getting-started)
